services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  app:
    build: .
    command: sh /app/entrypoint.sh
    # Le port 8000 n'est plus exposé à l'extérieur, seul NGINX y a accès.
    # ports:
    #   - "8000:8000"
    environment:
      PYTHONPATH: /app
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lab4db
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "labuser", "-d", "lab4db"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    depends_on:
      - app

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  produits-db:
    image: postgres:15
    environment:
      POSTGRES_DB: produits_db
      POSTGRES_USER: produits_user
      POSTGRES_PASSWORD: produits_pass
    ports:
      - "5434:5432"
    volumes:
      - produits_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "produits_user", "-d", "produits_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  produits-service:
    build: ./service-produits
    ports:
      - "8001:8000"
    environment:
      POSTGRES_DB: produits_db
      POSTGRES_USER: produits_user
      POSTGRES_PASSWORD: produits_pass
      POSTGRES_HOST: produits-db
      POSTGRES_PORT: 5432
    depends_on:
      produits-db:
        condition: service_healthy
    volumes:
      - ./service-produits:/app
    command: >
      sh -c "python manage.py migrate &&
             python load_data.py &&
             python manage.py runserver 0.0.0.0:8000"

  stock-db:
    image: postgres:15
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pass
    ports:
      - "5435:5432"
    volumes:
      - stock_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "stock_user", "-d", "stock_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  stock-service:
    build: ./service-stock
    ports:
      - "8002:8000"
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pass
      POSTGRES_HOST: stock-db
      POSTGRES_PORT: 5432
    depends_on:
      stock-db:
        condition: service_healthy
    volumes:
      - ./service-stock:/app
    command: >
      sh -c "python manage.py migrate &&
             python load_data.py &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
  redis_data:
  produits_data:
  stock_data:
