@startuml
title DSS - Get Performances API

actor Utilisateur
participant "Browser" as Browser
participant "PerformanceMagasinsAPI" as API
participant "UC3_Service" as Service
participant "Magasin, Vente, LigneVente" as Model

Utilisateur -> Browser : GET /api/v1/dashboard/
Browser -> API : GET /api/v1/dashboard/
API -> Service : get_indicateurs_par_magasin()
Service -> Model : requêtes ORM (Magasin, Vente, LigneVente)
Service <-- Model : données performances
API <-- Service : liste performances
Browser <-- API : 200 OK (JSON performances)
Utilisateur <-- Browser

@enduml