@startuml
title DSS - Get Stock Magasin API

actor Utilisateur
participant "Browser" as Browser
participant "StockMagasinAPI" as API
participant "UC2_Service" as Service
participant "StockLocal" as Model

Utilisateur -> Browser : GET /api/v1/stores/<id>/stock/
Browser -> API : GET /api/v1/stores/<id>/stock/
API -> Service : obtenir_stock_magasin(store_id)
Service -> Model : requête ORM (StockLocal)
Service <-- Model : stock magasin
API <-- Service : stock magasin (JSON)
Browser <-- API : 200 OK (JSON stock)
Utilisateur <-- Browser

@enduml