@startuml
title DSS - Get Produit API

actor Utilisateur
participant "Browser" as Browser
participant "ProduitUpdateAPI" as API
participant "UC4_Service" as Service
participant "Produit" as Model

Utilisateur -> Browser : GET /api/v1/products/<id>/
Browser -> API : GET /api/v1/products/<id>/
API -> Service : get_produit(produit_id)
Service -> Model : requête ORM (Produit)
Service <-- Model : données produit
API <-- Service : produit (JSON)
Browser <-- API : 200 OK (JSON produit)
Utilisateur <-- Browser

@enduml