@startuml vue-deploiement
' Vue de Déploiement - LOG430-Labo4 après Labo 4 (1 seule app Django)
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

title Vue de Déploiement - LOG430-Labo4 (Labo 4, 1 seule app Django)

node "Clients" {
  node "Navigateur Web" as browser {
    component user as "Utilisateur Web"
  }
}

node "Serveur d'Application (Docker Host)" as docker_host {
  node "Conteneur NGINX (Load Balancer)" as nginx {
    component nginx_proxy as "NGINX"
  }

  node "Conteneur Django App" as django_app {
    component app as "Django App"
  }

  node "Conteneur Redis (Cache)" as redis {
    component redis_srv as "Redis"
  }
  node "Conteneur PostgreSQL (DB)" as pg {
    component db_postgres as "PostgreSQL"
  }
  node "Conteneur Prometheus" as prometheus {
    component prometheus_srv as "Prometheus"
  }
  node "Conteneur Grafana" as grafana {
    component grafana_srv as "Grafana"
  }

  ' Liens réseau
  user -right-> nginx_proxy : HTTP
  nginx_proxy -down-> app : HTTP
  app -down-> redis_srv : TCP (cache)
  app -down-> db_postgres : TCP (ORM)
  prometheus_srv -down-> app : scrape /metrics
  grafana_srv -down-> prometheus_srv : requêtes dashboards
}

@enduml
