@startuml vue-deploiement
title Vue de Déploiement - Architecture avec API REST

skinparam linetype ortho
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

node "Clients" {
  node "Navigateur Web" as browser {
    component user as "Utilisateur Web"
  }
  node "Client Applicatif" as api_client {
    component external_system as "Système Externe / Mobile"
  }
}

node "Serveur d'Application (Docker Host)" as docker_host {
  node "Conteneur Web (Django)" as container_web {
    artifact "Application Django" as app_django {
        component web_ui as "Interface Web (Vues/Templates)"
        component rest_api as "API REST (DRF)"
    }
  }

  node "Conteneur Base de données" as container_db {
    component db_postgres as "PostgreSQL"
  }

  rest_api -- db_postgres : ORM
  web_ui -- db_postgres : ORM
}

user -right-> web_ui : HTTP/HTML
external_system -down-> rest_api : HTTP/JSON

@enduml
